### ISSUE TITLE
"can't adapt type 'CombinedExpression'" in admin filter

### ISSUE THREAD

**Issue by Datamance** [disqus/django-bitfield#89]
Getting an error with Django 1.11.21 and the latest PyPI release of this library (1.9.3) - 

`django.db.utils.ProgrammingError: can't adapt type 'CombinedExpression'`

When I try to filter by a flag in admin.

**Comment by timabbott** [comment]
@Datamance can you check whether this is fixed in the 1.9.5 release that went out today?

**Comment by vne** [comment]
@timabbott I just encountered the same issue in the same situation (trying to filter by flag in the admin) using Django 2.0.5 and django-bitfield 1.9.6.

**Comment by timabbott** [comment]
OK great.  I don't have a lot of time for debugging this (I don't use the Django admin) but I imagine this isn't a deep issue, and I'd happily merge a patch for it.

**Comment by timabbott** [comment]
I believe this is fixed in #103.

**Comment by WoLpH** [comment]
If this was indeed fixed in #103, it has been broken again in the mean time. It doesn't work for me on Django 2.2.15

**Comment by timabbott** [comment]
Essentially no development has happened since #103, so it seems more likely that it didn't fix your situation.  I'd encourage you to put together a reproducer and/or PR; I mostly only have time to review PRs and publish releases for this project.

**Comment by hardenchant** [comment]
I got this error too. Add quick fix at #118
